SEP_Med_Web/SEP_Med_Web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls')),
    path('', include('report.urls')),
    path('', include('administration.urls')),
    path('', include('news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SEP_Med_Web/news/urls.py
# urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Other URL patterns
    path('task_center/<int:page>/', views.task_center, name='task_center'),
    path('home/task_center/<int:page>/', views.home_task_center, name='home_task_center'),
    path('task_add/', views.task_add, name='task_add'),
    path('task_del/', views.task_del, name='task_del'),
    path('home/task_add/', views.home_task_add, name='home_task_add'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('upload_image_page/', views.upload_image_page, name='upload_image_page'),
    path('home/upload_image_page/', views.home_upload_image_page, name='home_upload_image_page'),
    path('reset_task_center/', views.reset_task_center, name='reset_task_center'),
    path('question/', views.question_page, name='question_page'),
    path('home/question/', views.home_question_page, name='home_question_page')
]

SEP_Med_Web/report/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = "report"

urlpatterns = [
    # Other URL patterns
    path('home/report', views.create_report_view, name='report'),
]

# 添加对媒体文件的处理
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SEP_Med_Web/news/models.py
from django.db import models
from users.models import User
from administration.models import Scene,SafetyIndicator



class Task(models.Model):
    task_id = models.IntegerField(primary_key=True, db_comment='任务ID')
    task_name = models.CharField(unique=True, max_length=30, db_comment='任务名称')
    task_state = models.ForeignKey('TaskStateTable', models.DO_NOTHING, db_column='task_state', db_comment='任务状态')
    scene = models.ForeignKey(Scene, on_delete=models.CASCADE, db_comment='应用场景（场景ID）')
    task_creator = models.ForeignKey(User, on_delete=models.CASCADE, db_column='task_creator', db_comment='任务创建人（用户ID）')
    task_create_time = models.DateTimeField(db_comment='任务创建时间')
    product_name = models.CharField(unique=True, max_length=20, db_comment='产品名称')
    product_version = models.CharField(max_length=20, blank=True, null=True, db_comment='产品版本号')
    product_description = models.CharField(max_length=200, blank=True, null=True, db_comment='产品描述')
    product_td = models.ImageField(upload_to='images/', db_column='product_TD', blank=True, null=True, db_comment='产品拓扑图')  # Field name made lowercase.
    product_ad = models.ImageField(upload_to='images/', db_column='product_AD', blank=True, null=True, db_comment='产品架构图')  # Field name made lowercase.
    app_ip = models.PositiveIntegerField(db_column='app_IP', blank=True, null=True, db_comment='应用IP')  # Field name made lowercase.
    app_domain_name = models.CharField(max_length=200, blank=True, null=True, db_comment='应用域名')
    app_starting_url = models.CharField(db_column='app_starting_URL', max_length=200, blank=True, null=True, db_comment='起始URL')  # Field name made lowercase.
    app_port = models.IntegerField(blank=True, null=True, db_comment='应用端口')
    app_name = models.CharField(max_length=30, blank=True, null=True, db_comment='应用名称')
    app_os_version = models.CharField(max_length=30, blank=True, null=True, db_comment='操作系统版本')

    class Meta:
        managed = True
        db_table = 'task'

class TaskEvaluation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, db_comment='用户ID')  # The composite primary key (user_id, task_id) found, that is not supported. The first column is selected.
    task = models.ForeignKey(Task, on_delete=models.CASCADE, db_comment='任务ID')
    task_evaluate_time = models.DateTimeField(db_comment='评审时间')

    class Meta:
        managed = True
        db_table = 'task_evaluation'
        unique_together = (('user', 'task'),)

class TaskOperation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, db_comment='用户ID')  # The composite primary key (user_id, task_id) found, that is not supported. The first column is selected.
    task = models.ForeignKey(Task, on_delete=models.CASCADE, db_comment='任务ID')
    task_operate_time = models.DateTimeField(db_comment='最后操作时间')

    class Meta:
        managed = True
        db_table = 'task_operation'
        unique_together = (('user', 'task'),)


class TaskSi(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE, primary_key=True, db_comment='任务ID')  # The composite primary key (task_id, si_id) found, that is not supported. The first column is selected.
    si = models.ForeignKey(SafetyIndicator, on_delete=models.CASCADE, db_comment='安全指标ID')

    class Meta:
        managed = True
        db_table = 'task_si'
        unique_together = (('task', 'si'),)


class TaskStateTable(models.Model):
    task_state_id = models.IntegerField(primary_key=True, db_comment='任务状态')
    task_state_name = models.CharField(max_length=30, db_comment='任务状态名称')

    class Meta:
        managed = True
        db_table = 'task_state_table'


# class User(models.Model):
#     user_id = models.IntegerField(primary_key=True, db_comment='用户ID')
#     user_account = models.CharField(unique=True, max_length=30, db_comment='用户账号')
#     user_password = models.CharField(max_length=30, db_comment='用户密码')
#     user_name = models.CharField(unique=True, max_length=20, db_comment='用户账号')
#     user_authority = models.IntegerField(db_comment='用户权限')
#     user_email = models.CharField(max_length=30, blank=True, null=True, db_comment='用户邮箱')
#     user_phone = models.CharField(max_length=11, blank=True, null=True, db_comment='用户电话号码')

#     class Meta:
#         managed = True
#         db_table = 'user'

SEP_Med_Web/news/views.py
import os
from django import forms
from django.conf import settings
from django.db import IntegrityError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.core.cache import cache
from .models import TaskSi, User  # 导入自定义用户模型
from .models import Task
from .models import Scene
from .models import TaskStateTable
from .models import SafetyIndicator
from .models import Scene
from question_answer.chatbot_graph import *
import ipaddress


handler = ChatBotGraph()

def login_view(request):
    if request.method == 'POST':
        user_account = request.POST['user_account']
        password = request.POST['password']
        print(request.POST)
        print(user_account)
        print(password)

        # 使用自定义用户模型进行身份验证
        try:
            user = User.objects.get(user_account=user_account)
            if user.user_password == password:
                # 如果用户名和密码匹配，登录用户
                # login(request, user)
                # 重定向到成功页面或主页
                return redirect('/home/')
            else:
                # 如果密码不匹配，返回到登录页面并显示错误消息
                return render(request, 'news/login.html', {'error_message': '用户名或密码错误'})
        except User.DoesNotExist:
            # 如果找不到具有提供的用户名的用户，返回到登录页面并显示错误消息
            return render(request, 'news/login.html', {'error_message': '未知用户名，请检查用户名或注册账户'})

    return render(request, 'news/login.html')

def logon_view(request):
    return render(request, 'news/logon.html')

def home(request):
    return render(request, 'news/home.html')

def task_center(request, page):
    all_task_data = Task.objects.all().order_by("task_id")
    all_task_state_data = TaskStateTable.objects.all()
    search_data = {}
    search_data["task_state"] = "全部"
    # Initialize variables
    pre_list = []
    next_list = []
    previous_page = None
    next_page = None
    page_num = None

    if request.method =='POST':
        search_filter = {}
        search_data = {}
        task_id = request.POST['task_id']
        task_name = request.POST['task_name']
        state_selection = request.POST['dropdownMenu-value']
        state_selection_num = TaskStateTable.objects.filter(task_state_name = state_selection).first()
        start_time = request.POST['start_time']
        end_time = request.POST['end_time']
        # print(task_id)
        # print(task_name)
        # print(state_selection)
        # print(start_time)
        # print(end_time)
        # 查询
        if task_id:
            search_filter["task_id__contains"] = task_id
            search_data["task_id"] = task_id
        if task_name:
            search_filter["task_name__contains"] = task_name
            search_data["task_name"] = task_name
        if state_selection_num:
            search_filter["task_state"] = state_selection_num 
            search_data["task_state"] = state_selection
        else:
            search_data["task_state"] = "全部"
        if start_time:
            search_filter["task_create_time__gte"] = start_time
            search_data["start_time"] = start_time
        if end_time:
            search_filter["task_create_time__lte"] = end_time
            search_data["end_time"] = end_time
        all_task_data = Task.objects.filter(**search_filter).order_by('task_id')
        print(state_selection_num)
        # 将结果存储到缓存，过期时间可以根据实际情况调整
        cache.set('task_center_data', (all_task_data, all_task_state_data, search_data, pre_list, next_list, previous_page, next_page, page_num), timeout=300)
        # 搜索后默认跳转到第一页
        page = 1

    # 检查是否有缓存数据
    cached_data = cache.get('task_center_data')

    if cached_data:
        # 如果有缓存数据，直接使用缓存数据
        all_task_data, all_task_state_data, search_data, pre_list, next_list, previous_page, next_page, page_num = cached_data
        
    for task in all_task_data:
        task.task_create_time = task.task_create_time.strftime("%Y-%m-%d %H:%M:%S")

    # 实现分页显示
    # 获取传来的page
    # 如果用户未输入page参数，默认为1
    if page == None:
        page = 1
    page_max_item = 7   # 一页最多多少行数据
    start = (page - 1) * page_max_item  # 切片开始位
    end = page * page_max_item  #切片结束位
    total = all_task_data.count()   # 计数
    all_task_data =  all_task_data[start:end]

    # 页码
    page_num = int(total / page_max_item)
    if total % page_max_item:
        page_num += 1

    x = 1
    y = 5
    if page <= x:
        pre_list = range(1, page)
    else:
        pre_list = range(page - x, page)
    
    if page > page_num - y:
        next_list = range(page + 1, page_num + 1)
    else:
        next_list = range(page + 1, page + y + 1)
    if page == 1:
        previous_page = 1
        next_page = page + 1
    elif page == page_num:
        previous_page = page - 1
        next_page = page_num
    else:
        previous_page = page - 1
        next_page = page + 1

    print(page)
    print(previous_page)
    print(next_page)

    return render(request, 'news/task_center.html', 
                  {"task_data": all_task_data, 
                   "task_state_data": all_task_state_data, 
                   "search_data": search_data,
                   "pre_list": pre_list,
                   "next_list": next_list,
                   "previous_page": previous_page, 
                   "now_page": page,
                   "next_page": next_page,
                   "first_page": 1,
                   "last_page": page_num})

def home_task_center(request, page):
    # 获取传来的page
    # 如果用户未输入page参数，默认为1
    if page == None:
        page = 1
    print(page)
    return render(request, 'news/home_task_center.html', {"page": page})

def ip_to_int(ip_address):
    try:
        ip_int = int(ipaddress.IPv4Address(ip_address))
        return ip_int
    except ipaddress.AddressValueError:
        # 处理无效的 IP 地址
        return None

def task_add(request):
    all_scene_data = Scene.objects.all()
    all_si_data = SafetyIndicator.objects.all()
    display_si = SafetyIndicator.objects.filter(si_state=1).first()
    if request.method == "POST":
        if 'submit_all' in request.POST:
            try:
                new_task = Task()
                task_name = request.POST.get('task_name')
                scene_name = request.POST.get('dropdownMenu1-value')
                product_name = request.POST.get('product_name')
                '''
                new_img = Task(
                    product_TD = request.FILES.get('product_TD'),  # 拿到图片
                    product_AD = request.FILES.get('product_AD')
                )
                # new_img.save()  # 保存图片'''
                product_version = request.POST.get('product_version')
                product_description = request.POST.get('product_description')
                app_IP = request.POST.get('app_IP')
                app_DN = request.POST.get('app_DN')
                app_starting_url = request.POST.get('app_starting_url')
                app_port = request.POST.get('app_port')
                app_name = request.POST.get('app_name')
                app_os_version = request.POST.get('app_os_version')

                if Task.objects.all().count() == 0:
                    new_task.task_id = 1
                else:
                    new_task.task_id = Task.objects.latest('task_id').task_id + 1   # 获得最大的id并加一
                new_task.task_name = task_name
                new_task.task_state = TaskStateTable.objects.filter(task_state_name="未开始").first()   # 默认状态是0未开始
                new_task.scene = Scene.objects.filter(scene_name=scene_name).first() # 连表查询改为id
                new_task.task_creator = User.objects.filter(user_name='金木').first()  # TODO 需要传递登录信息
                new_task.product_name = product_name
                if product_version:
                    new_task.product_version = product_version
                if product_description:
                    new_task.product_description = product_description
                if app_IP:
                    new_task.app_ip = ip_to_int(app_IP)
                if app_DN:
                    new_task.app_domain_name = app_DN
                if app_starting_url:
                    new_task.app_starting_url = app_starting_url
                if app_port:
                    new_task.app_port = app_port
                if app_name:
                    new_task.app_name = app_name
                if app_os_version:
                    new_task.app_os_version = app_os_version
                new_task.save()


                print(Task.objects.latest('task_id').task_id + 1)
                print(task_name)
                print(TaskStateTable.objects.filter(task_state_name="未开始").first())
                print(Scene.objects.filter(scene_name=scene_name).first())
                print(scene_name)
                print(product_name)
                print(product_version)
                print(product_description)
                print(app_IP)
                print(ip_to_int(app_IP))
                print(app_DN)
                print(app_starting_url)
                print(app_port)
                print(app_name)
                print(app_os_version)

                # 可以创建多个安全指标，并且实现连表查询，插入多条记录
                si_category = request.POST.get('dropdownMenu2-value')   # 获取多选的字符串
                si_category_list = si_category.split('/')               # 分割获得列表
                # 创建插入多条记录的列表
                new_task_si_list = []
                for si in si_category_list:
                    new_task_si_list.append(TaskSi(
                        task=Task.objects.latest('task_id'),    # 获得最大的id
                        si=SafetyIndicator.objects.filter(si_name=si).first()))
                # 一次插入多条记录
                TaskSi.objects.bulk_create(new_task_si_list)

                return redirect('/upload_image_page/')
            
            except IntegrityError as e:
                # 处理唯一性约束违反的情况
                # 这里你可以根据具体情况选择如何提醒用户，例如弹出警告窗口或在页面上显示警告信息
                error_message = str(e)
                print(error_message)

SEP_Med_Web/news/templates/news/home.html
{% extends 'news/home_base.html' %}

{% block head %}
  <!-- 必须添加的bootstarp的时间控件资源路径 -->
  <link href="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet"> 
  <script src="https://cdn.bootcdn.net/ajax/libs/moment.js/2.25.3/moment-with-locales.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
{% endblock %}  

{% block style %}
{% endblock %}  

{% block body %}
  <div class="welcome-container">
    <div class="welcome-message">欢迎来到医学信息安全评价</div>
  </div>
{% endblock %} 

{% block script %}

{% endblock %} 

SEP_Med_Web/news/templates/news/home_question.html
{% extends 'news/home_base.html' %}

{% block body %}
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="/question/"></iframe>
    </div>
{% endblock %}

SEP_Med_Web/news/templates/news/home_si.html
{% extends 'news/home_base.html' %}

{% block style %}
{% endblock %}  

{% block body %}
    <div class="row">
      <div class="col-md-3 col-md-offset-1" style="margin-top: 40px;">
        <div class="dropdown">
          <label class="control-label">安全指标类型</label>
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="width: 195px;">
            选择
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
            <!-- 需要传入数据库场景列表 -->
            <li><a href="#" style="width: 195px;">全部</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#" style="width: 195px;">个人家庭</a></li>
            <li><a href="#" style="width: 195px;">医院社区</a></li>
            <li><a href="#" style="width: 195px;">移动救治</a></li>
          </ul>
        </div> 
      </div>  
      <div class="col-md-4" style="background-color: green; margin-top: 40px;">
        <label class="control-label">安全指标类型</label>
        <div class="form-group">
          <div class="input-group">
            <input
              type="text"
              class="form-control"
              id="si_name"
              name="si_name"
              placeholder="请输入"
            />
          </div>
        </div>
      </div>
    </div> 
{% endblock %} 

SEP_Med_Web/news/templates/news/home_task_add.html
{% extends 'news/home_base.html' %}

{% block body %}
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="/task_add/"></iframe>
    </div>
{% endblock %}

SEP_Med_Web/news/templates/news/home_task_center.html
{% extends 'news/home_base.html' %}

{% block body %}
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="/task_center/{{ page }}/"></iframe>
    </div>
{% endblock %}

SEP_Med_Web/news/templates/news/home_upload_image.html
{% extends 'news/home_base.html' %}

{% block body %}
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="/upload_image_page/"></iframe>
    </div>
{% endblock %}

SEP_Med_Web/news/templates/news/task_center.html
<!DOCTYPE html>
<html>
  <head>
    <title>医学信息安全评价主页</title>
    <meta charset="UTF-8" />
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <!-- 兼容IE浏览器 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- 引入 Bootstrap的css -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}" />
    <!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <!-- 包括所有已编译的插件 -->
    <script src="{% static 'plugins/bootstrap-3.4.1-dist/js/bootstrap.js' %}"></script>
    <!-- 必须添加的bootstarp的时间控件资源路径 -->
    <link href="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet"> 
    <script src="https://cdn.bootcdn.net/ajax/libs/moment.js/2.25.3/moment-with-locales.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

  </head>

  <body>
    <div class="container-fluid">
    <div class="row">
      <form method="post">
      {% csrf_token %}
      <div class="col-md-2 col-sm-2 col-xs-2" style="margin-top: 40px; margin-left: 40px;">
        <div class="form-group">
          <div class="row">
            <label class="control-label">任务ID</label>
            <div class="input-group">
              <input
                type="text"
                maxlength="8"
                class="form-control"
                id="task_id"
                name="task_id"
                placeholder="请输入"
                value="{{ search_data.task_id }}"
              />
            </div>
          </div> 
        </div>
      </div>  


      <div class="col-md-2 col-sm-2 col-xs-2" style="margin-top: 40px;">
        <div class="form-group">
          <div class="row">
            <label class="control-label">任务名称</label>
            <div class="input-group">
              <input
                type="text"
                maxlength="30"
                class="form-control"
                id="task_name"
                name="task_name"
                placeholder="请输入"
                value="{{ search_data.task_name }}"
              />    
            </div>
          </div> 
        </div>
      </div>

      <div class="col-md-1 col-sm-1 col-xs-1" style="margin-top: 40px;">
        <label class="control-label">状态</label>
        <div class="dropdown">
          <input type="hidden" id='dropdownMenu-value' name="dropdownMenu-value" value=全部> 
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            {{ search_data.task_state }}
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu dropdown-menu-left" aria-labelledby="dropdownMenu1">
            <!-- 需要传入数据库场景列表 -->
            <li><a href="#">全部</a></li>
            <li role="separator" class="divider"></li>
            {% for task_state in task_state_data %}
              <li><a href="#">{{ task_state.task_state_name }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div> 

      <div class="col-md-2 col-sm-2 col-xs-2" style="margin-top: 40px;">
        <div class="form-group">
          <label>开始时间</label>
          <!--指定 date标记-->
          <div class='input-group date' id='datetimepicker1'>
            <input type='text' class="form-control" id="start_time" name="start_time" value={{ search_data.start_time }} />
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>

      <div class="col-md-2 col-sm-2 col-xs-2" style="margin-top: 40px;">
        <div class="form-group">
          <label>结束时间</label>
          <!--指定 date标记-->
          <div class='input-group date' id='datetimepicker2'>
            <input type='text' class="form-control" id="end_time" name="end_time" value={{ search_data.end_time }} />
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>

      <div class="col-md-1 col-sm-1 col-xs-1" style="margin-top: 64px;">
        <button type="submit" class="btn btn-primary btn-block">
          查询
        </button>
      </div>   
      
      <div class="col-md-1 col-sm-1 col-xs-1" style="margin-top: 64px;">
        <button type="reset" class="btn btn-default btn-block">
          <a href={% url 'reset_task_center' %}>
          重置
        </button>
      </div> 
    </form>
    </div> 

    <div class="container-fluid">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" onclick="change_add_URL()">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                创建任务
            </a>
        </div>
        <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
                    任务列表
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>任务ID</th>
                        <th>任务名称</th>
                        <th>任务状态</th>
                        <th>应用场景</th>
                        <th>评审人员</th>
                        <th>创建时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for task in task_data %}
                    <tr>
                        <td>{{ task.task_id }}</td>
                        <td>{{ task.task_name }}</td>
                        <td>{{ task.task_state.task_state_name }}</td>
                        <td>{{ task.scene.scene_name }}</td>
                        <td>{{ task.task_creator.user_name }}</td>
                        <td>{{ task.task_create_time }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="{% url 'report:report' %}?task_id={{ task.task_id }}">查看</a>
                            {% if task.task_state.task_state_name  == '已完成' %}
                              <a class="btn btn-primary btn-xs">上传报告</a>
                              <a class="btn btn-primary btn-xs">检测报告</a>
                            {% endif %}
                            {% if task.task_state.task_state_name  == '未开始' %}
                              <a class="btn btn-primary btn-xs">派发</a>
                              <a class="btn btn-danger btn-xs" href="/task_del/?task_id={{ task.task_id }}">删除</a>
                            {% endif %}
                            {% if task.task_state.task_state_name  == '评审通过' %}
                              <a class="btn btn-primary btn-xs">复核</a>
                            {% endif %}
                            {% if task.task_state.task_state_name  == '检测中' %}
                              <a class="btn btn-primary btn-xs">评估安全指标</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-4 col-md-offset-8" style="margin-top: 64px;">
      <!-- bootstrap 分页 -->
      <ul class="pagination" 
          style="
          position: fixed;
          bottom: 0;
          height: 40px;
          width: 100%;
          text-align: center;">
        <li><a href="/task_center/{{ first_page }}/" aria-label="First"><span aria-hidden="true">««</span></a></li>
        <li><a href="/task_center/{{ previous_page }}/" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
        {% for this_page in pre_list %}
          <li><a href="/task_center/{{ this_page }}/">{{ this_page }}</a></li>
        {% endfor %}
        <li class="active"><a href="/task_center/{{ now_page }}/">{{ now_page }}</a></li>
        {% for this_page in next_list %}
          <li><a href="/task_center/{{ this_page }}/">{{ this_page }}</a></li>
        {% endfor %}
        <li><a href="/task_center/{{ next_page }}/" aria-label="Next"><span aria-hidden="true">»</span></a></li>
        <li><a href="/task_center/{{ last_page }}/" aria-label="Last"><span aria-hidden="true">»»</span></a></li>
        
      </ul>
    </div> 
    

  </div>

    <script>
      $(function () {
        var picker1 = $('#datetimepicker1').datetimepicker({
            format: 'YYYY-MM-DD',
            locale: moment.locale('zh-cn'),
            //minDate: '2016-7-1'
        });
        var picker2 = $('#datetimepicker2').datetimepicker({
            format: 'YYYY-MM-DD',
            locale: moment.locale('zh-cn')
        });
        //动态设置最小值
        picker1.on('dp.change', function (e) {
            picker2.data('DateTimePicker').minDate(e.date);
        });
        //动态设置最大值
        picker2.on('dp.change', function (e) {
            picker1.data('DateTimePicker').maxDate(e.date);
        });
      });
    
      $(document).ready(function() {
        // 监听下拉菜单中的选项点击事件
        $('.dropdown-menu a').on('click', function() {
          // 获取被点击的选项文本
          var selectedOption = $(this).text();
          // 设置下拉菜单按钮上显示的文本为选中的选项文本
          $('#dropdownMenu1').html(selectedOption + ' <span class="caret"></span>');
          //设置input中的value
          $('#dropdownMenu-value').val(selectedOption);
        });
      });
      // 在iframe内的JavaScript中
      function change_add_URL(newURL) {
        // 请求父级页面修改URL
        window.parent.postMessage({ type: 'change_add_URL', newURL: '/home/task_add/' }, '*');
      }
    </script>
  </body>
</html>